-
  name: UDP control
  hosts: all
  vars:
    packages:
      - name: python3-pip
        required: True
      - name: net-tools
        required: True
      - name: python-setuptools
        required: True
      - name: python3-setuptools
        required: True
  tasks:
    - name: Install "{}" on Debian
      apt:
        name: "{}"
        state: present
      when: ansible_os_family == "Debian" and item.required == True
      loop: "{}"

    - name: Install pymongo
      pip:
        name: pymongo
        executable: pip3
      when: ansible_os_family == "Debian"
      
    - name: Sent udpclient package
      copy:
        src: /app/ansiblepackages/udpclient-2022.06.30.x86_64.deb
        dest: /root/udpclient-2022.06.30.x86_64.deb
      when: ansible_os_family == "Debian"
      
    - name: Install package
      command: /usr/bin/dpkg -i /root/udpclient-2022.06.30.x86_64.deb
      when: ansible_os_family == "Debian"
      
    - name: Change udp server ip address
      lineinfile:
        path: /etc/systemd/system/udpclient.service
        regexp: '^ExecStart='
        line: ExecStart=/usr/bin/python3 /root/client/udpclient.py {}
        owner: root
        group: root
      when: ansible_os_family == "Debian"
      
    - name: Restart udpclient with daemon_reload
      systemd:
        state: restarted
        daemon_reload: yes
        name: udpclient.service
      when: ansible_os_family == "Debian"