---
- hosts: all
  gather_facts: yes
  tasks:
  - name: Distribution
    debug: msg="{{ ansible_distribution }}"
  - name: Distribution version
    debug: msg="{{ ansible_distribution_version}}"
  - name: Distribution family
    debug: msg="{{ ansible_os_family }}"