-
  name: UDP control
  hosts: all
  tasks:
    - name: Check Distribution family before uninstall
      debug: msg="{{ ansible_os_family }}"
 
    - name: Stop udpclient daemon
      systemd:
        state: stopped
        name: udpclient.service
 
    - name: Uninstall udpclient for Debian OS
      apt:
        name: udpclient-l12cm
        state: absent
      when: ansible_os_family == "Debian"
      
    - name: Uninstall udpclient for RedHat OS
      yum:
        name: udpclient
        state: absent
      when: ansible_os_family == "RedHat"

    - name: Reload daemon
      systemd:
        daemon_reload: yes