-
  name: l12-metrics uninstall
  hosts: all
  tasks:
    - name: Check Distribution family before uninstall
      debug: msg="{{ ansible_os_family }}"
 
    - name: Stop l12-metrics daemon
      systemd:
        state: stopped
        name: l12-metrics.service
 
    - name: Uninstall l12-metrics for Debian OS
      apt:
        name: l12-metrics
        state: absent
      when: ansible_os_family == "Debian"
      
    - name: Uninstall l12-metrics for RedHat OS
      yum:
        name: l12-metrics
        state: absent
      when: ansible_os_family == "RedHat"

    - name: Reload daemon
      systemd:
        daemon_reload: yes