---
- name: Install Python3
  hosts: all
  vars:
    packages:
      - name: python3
        type: all
      - name: python3-pip
        type: all
      - name: python3-setuptools
        type: all

  tasks:
          - name: Install "{{ item.name }}" on Debian
            apt:
              name: "{{ item.name }}"
              state: present
            when: ansible_os_family == "Debian" and (item.type == "all" or item.type == "deb")
            loop: "{{ packages }}"

          - name: Install "{{ item.name }}" on RedHat
            yum:
              name: "{{ item.name }}"
              state: present
            when: ansible_os_family == "RedHat"  and (item.type == "all" or item.type == "rpm")
            loop: "{{ packages }}"